stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
    - data/raw/weatherAUS.csv
    - scripts/preprocess.py
    outs:
    - data/processed/weather_cleaned.csv
  train:
    cmd: python scripts/train.py
    deps:
    - data/processed/weather_cleaned.csv
    - scripts/train.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
