name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      # ESSA ETAPA É O QUE ESTÁ FALTANDO:
      - name: Install dependencies
        run: |
          pip install pandas xgboost scikit-learn matplotlib joblib

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Configura o DVC
          dvc remote modify origin --local user $DAGSHUB_USER
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          
          # Tenta baixar, mas se der erro de cache, não para a execução (|| true)
          dvc pull data/raw/weatherAUS.csv.dvc || true
          
          # O -f (force) obriga a rodar os scripts mesmo sem o cache. 
          # O GitHub vai gerar novos arquivos limpos e o novo modelo na hora.
          dvc repro -f 
          
          # Relatório do CML
          echo "## 🚀 Relatório de Treino Automático" > report.md
          echo "Acurácia: $(cat metrics.json)" >> report.md
          echo "### 📉 Matriz de Confusão" >> report.md
          echo "![](./confusion_matrix.png)" >> report.md
          cml comment create report.md