name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      # ESSA ETAPA É O QUE ESTÁ FALTANDO:
      - name: Install dependencies
        run: |
          pip install pandas xgboost scikit-learn matplotlib joblib

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Configura o DVC
          dvc remote modify origin --local user $DAGSHUB_USER
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          
          dvc pull data/raw/weatherAUS.csv.dvc --force                        # Baixa os dados do DagsHub
          dvc repro                        # Roda a pipeline (agora com pandas instalado!)
          
          # Cria o relatório
          echo "## 🚀 Relatório de Treino Automático" > report.md
          echo "Acurácia: $(cat metrics.json)" >> report.md
          echo "### 📉 Matriz de Confusão" >> report.md
          echo "![](./confusion_matrix.png)" >> report.md
          
          cml comment create report.md