name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # <--- Isso força o download de TODAS as branches!
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - name: Install dependencies
        run: |
          pip install pandas xgboost scikit-learn matplotlib joblib

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Diz para o GitHub onde os dados moram (O link do DagsHub)
          # O --force serve para garantir que ele sobrescreva qualquer config antiga
          dvc remote add origin https://dagshub.com/guiga-sa/novo_teste_mlops2.dvc --force

          # 2. Passa as chaves de acesso que estão nos Secrets
          dvc remote modify origin --local user $DAGSHUB_USER
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          dvc remote modify origin --local auth basic
          
          # 3. Agora sim, ele vai ter o mapa e a chave para buscar os dados
          dvc pull data/raw/weatherAUS.csv.dvc
          dvc repro -f
          git fetch --prune

          # 4. Gera o relatório
          echo "##  Relatório de Treino Automático (CML)" > report.md
          echo "Acurácia: $(cat metrics.json)" >> report.md
          echo "###  Matriz de Confusão" >> report.md
          echo "![](./confusion_matrix.png)" >> report.md
          echo "### Comparação de Métricas (Atual vs Main)" >> report.md
          dvc metrics diff --md main >> repots.md 

          cml comment create report.md